name: flutter_download_manager
description: A Flutter package to download files to Android Downloads folder with notifications.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.2
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  awesome_notifications: ^0.11.0
  shared_preferences: ^2.5.5



flutter:
  plugin:
    platforms:
      android:
        package: com.fdm.flutter_download_manager
        pluginClass: FlutterDownloadManagerPlugin