name: smart_download_manager_plus
description: A Flutter package to download files to Android Downloads folder with notifications.
version: 1.0.3
homepage: https://github.com/MuhammadAli224/smart_download_manager_plus
repository: https://github.com/MuhammadAli224/smart_download_manager_plus
issue_tracker: https://github.com/MuhammadAli224/smart_download_manager_plus/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

topics:
  - download
  - file-manager
  - dio
  - offline
  - notifications

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.2
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  awesome_notifications: ^0.11.0
  shared_preferences: ^2.5.5
  plugin_platform_interface: ^2.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fdm.flutter_download_manager
        pluginClass: FlutterDownloadManagerPlugin
      ios:
        pluginClass: FlutterDownloadManagerPlugin